import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

let transporter = null;

if (process.env.EMAIL_HOST && process.env.EMAIL_USER && process.env.EMAIL_PASS) {
  transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST,
    port: parseInt(process.env.EMAIL_PORT || '587'),
    secure: process.env.EMAIL_SECURE === 'true',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });
  console.log('✅ Email service initialized');
} else if (process.env.EMAIL_KEY) {
  // Gmail App passwords or similar single-key setups
  transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER || '',
      pass: process.env.EMAIL_KEY,
    },
  });
  console.log('✅ Email service initialized (Gmail)');
} else {
  console.warn('⚠️  Email credentials not configured. Email sending will be simulated.');
}

export async function sendComplaintEmail(complaintData) {
  const { name, email, message, fraudScore, riskLevel, companyName, description } = complaintData;

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: 'Segoe UI', sans-serif; background: #0a0f0d; color: #e2f5ea; padding: 20px; }
        .container { max-width: 600px; margin: 0 auto; background: #141e19; border: 1px solid rgba(0,255,136,0.15); border-radius: 16px; padding: 32px; }
        .header { text-align: center; padding-bottom: 20px; border-bottom: 1px solid rgba(0,255,136,0.1); margin-bottom: 24px; }
        .header h1 { color: #00ff88; font-size: 20px; margin: 0; }
        .score { font-size: 48px; font-weight: 900; color: ${fraudScore > 50 ? '#ff3860' : '#00ff88'}; text-align: center; margin: 16px 0; }
        .field { margin-bottom: 16px; }
        .label { font-size: 12px; text-transform: uppercase; color: #64748b; letter-spacing: 1px; margin-bottom: 4px; }
        .value { font-size: 14px; color: #e2f5ea; background: rgba(0,255,136,0.05); padding: 10px; border-radius: 8px; border: 1px solid rgba(0,255,136,0.08); }
        .footer { text-align: center; margin-top: 24px; font-size: 12px; color: #64748b; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🛡️ AI Cyber Trust Shield — Complaint Report</h1>
        </div>
        <div class="score">${fraudScore}/100</div>
        <div class="field"><div class="label">Reporter Name</div><div class="value">${name}</div></div>
        <div class="field"><div class="label">Reporter Email</div><div class="value">${email}</div></div>
        <div class="field"><div class="label">Company Reported</div><div class="value">${companyName || 'Not specified'}</div></div>
        <div class="field"><div class="label">Risk Level</div><div class="value">${riskLevel}</div></div>
        <div class="field"><div class="label">Suspicious Message</div><div class="value">${message?.slice(0, 500) || 'N/A'}</div></div>
        ${description ? `<div class="field"><div class="label">Additional Details</div><div class="value">${description}</div></div>` : ''}
        <div class="footer">
          <p>This report was generated by AI Cyber Trust Shield</p>
          <p>Timestamp: ${new Date().toISOString()}</p>
        </div>
      </div>
    </body>
    </html>
  `;

  if (!transporter) {
    console.log('📧 [SIMULATED] Email would be sent to:', email);
    console.log('   Subject: Complaint Filed — AI Cyber Trust Shield');
    return { sent: true, simulated: true };
  }

  try {
    const info = await transporter.sendMail({
      from: `"AI Cyber Trust Shield" <${process.env.EMAIL_USER || 'noreply@cybertrust.ai'}>`,
      to: email,
      subject: `🛡️ Complaint Filed — Fraud Score: ${fraudScore}/100 — AI Cyber Trust Shield`,
      html: htmlContent,
    });
    console.log('📧 Email sent:', info.messageId);
    return { sent: true, messageId: info.messageId };
  } catch (error) {
    console.error('Email send error:', error.message);
    return { sent: false, error: error.message };
  }
}
